# Use postgres/example user/password credentials
version: '3.8'

volumes:
  post-db:

services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - post-db:/data/db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
