# Use postgres/example user/password credentials
version: '3.1'

volumes:
  post-db:

services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - post-db:/data/db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  go_api:
    build: .
    ports:
      - '10000:10000'
    depends_on:
      - postgres_db
