name : Deploy LIVE
on:
  push:
    branches :
    - master

jobs:
  build :
    name: Checkout & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Linter
        uses: github/super-linter@latest
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  